---
title: "Collaborator_Tasks"
author: "Leroy_Bondhus"
date: "February 16, 2021"
output: html_document
---

## USING THIS FILE FOR ORGANIZATION
* Feel free to add ToDo items to you own list
* If adding ToDo item to someone else's list add your name to request in parentheses
* This file is NOT meant to track progress (task requestor, usually Leroy, can remove items from completed section. This section only so updates are more easily noticed. )

## Leroy's Tasks
### To Do
* Organize github repository for collaboration
* Check that Roshni and Yenifer can pull,edit,push,commit to this document
* Check that Roshni and Yenifer can create their own Rmd workspaces in this repo
* Assign specific tasks to Roshni and Yenifer 

### Completed
*
---------------

## Roshni's Tasks
### ToDo
* Draft specificy measure comparison methods section on shared google doc (Draft of Paper) (Leroy) 
* research different specificity measures
*     + make table of measure's 1.name or symbol 2.equation 3.source publication 4. notes (shoot for ~2-5) (Leroy)
*     + write functions for each measure for ease of use (Leroy)
* functionalize dropping different tissues from the dataset and being able to calculate specificity score
*     + draft some potential measurements and figures that can be used to compare results (Leroy)

### Progress
* finished table comparing specificity scores
* functionalized dropping different tissues from te matrix

### Completed
* Move this item to completed (Leroy)
---------------


## Yenifer's Tasks
### ToDo
* Draft sample similarity/distance comparison methods section of shared google doc (Draft of Paper) (Leroy)
* Literature search for sample similarity/distance for gene expression (Leroy)
*     + make table of measure's 1.name or symbol 2.equation 3.source publication 4. notes (shoot for ~2-5) (Leroy)
*         +include binary specificity cutoff (Leroy)
*     + write functions for each measure for ease of use (Leroy)
* Write functions to generate a tree from a distance matrix (Leroy)
*     + requires use of -list- objects in R, discuss with Leroy

### Completed
* Move this item to completed (Leroy)
* Added real time
---------------




