---
title: "Yenifer_Workspace"
output: html_document
---

```{r}
GTEX.data <-read.csv("/Users/yeniferhernandez/Desktop/Arboleda_Lab/gtex_medians_PC_only_wo_MT.csv", header = TRUE, sep=",")  
num_cols <- unlist(lapply(GTEX.data , is.numeric))
GTEX.data_num <- GTEX.data[ , num_cols]  
GTEX.data_num <- GTEX.data_num[,-1]
mean_exp <- apply(GTEX.data_num , 1, mean) 
median_exp <- apply(GTEX.data_num , 1, median)
sd_exp <- apply(GTEX.data_num , 1, sd)
GTEX_log <- log(GTEX.data_num + 1)# log of GTEX gene expression 
mean_log <- apply(GTEX_log , 1, mean) 
sd_log <- apply(GTEX_log , 1, sd) 
sd_log<- abs(sd_log)
median_log <- apply(GTEX_log , 1, median)
gene_sd <- cbind.data.frame(GTEX.data[,2],sd_log) 
colnames(gene_sd) <- c("Description","Standard Deviation Log") 
Name <- GTEX.data[,1]

#cosine similarity matrix 
cosine_similarity_matrix <- function(data_set,col_num) {
cosine_simi<- matrix(0, nrow = col_num, ncol = col_num)
for(y in 1:col_num) {
  for(x in 1:col_num) {
product_xy <- data_set[,x] * data_set[,y]
sum_xy <- sum(product_xy)
magnitude_x <- data_set[,x]^2
magnitude_x<- sum(magnitude_x)
magn_x <- sqrt(magnitude_x)
magnitude_y <- data_set[,y]^2
magnitude_y <- sum(magnitude_y)
magn_y <- sqrt(magnitude_y)
magn_z <- magn_x * magn_y
cos_sin <-  sum_xy/magn_z
colnames(cosine_simi)<-colnames(data_set)
rownames(cosine_simi)<-colnames(GTEX.data_num)
cosine_simi[x,y] <- cos_sin


  }
}
View(cosine_simi)

}
#actual standard deviations matrix
actual_sdev_matrix<- function(data,mean,sd,row_num,col_num) {
actu_sdev <- matrix(0, nrow = row_num, ncol = col_num)
for(j in 1:col_num) {
  for(i in 1:row_num)  {
   actu_sdev[i,j] <- (data[i,j] - mean[i])/sd[i]
}      
}
actu_sdev <-replace(actu_sdev, is.na(actu_sdev), 0)
n <- matrix(0, nrow = col_num, ncol = col_num)
dot_product_matrix <- matrix(0, nrow = col_num, ncol = col_num)
for(G1 in 1:col_num) {
  for(G2 in 1:col_num)  {
   n <- actu_sdev[,G1]*actu_sdev[,G2]
   dot_product_matrix [G2,G1]<- sum(n)
}
}
diag_val <- diag(dot_product_matrix )
diag_matrix <- data.matrix(diag_val)
simi_matrix<- matrix(0, nrow = col_num, ncol = col_num)
for(G1 in 1:col_num) {
  for(G2 in 1:col_num)  {
 simi_matrix[G1,G2]<-  dot_product_matrix [G1,G2]/(max(diag_matrix [G1],diag_matrix [G2]))
}
}
colnames(simi_matrix)<-colnames(data)
rownames(simi_matrix)<-colnames(data)
View(simi_matrix)


}
#Pearson's coefficients function matrix 
pearson_coefficient_matrix <- function(data_set,col_num) {
  pearson_matrix<- matrix(0, nrow = col_num, ncol = col_num)
  for(y in 1:col_num) {
     for(x in 1:col_num)  {
  mean_x <- mean(data_set[,x])
  mean_y <- mean(data_set[,y])
  minus_x <- (data_set[,x] - mean_x)
  minus_y <- (data_set[,y] - mean_y)
  product_xy <- minus_x*minus_y
  sum_xy<- sum(product_xy)
  power_x <- minus_x ^ 2 
  sum_power_x <-sum(power_x)
  square_x <- sqrt(sum_power_x)
  power_y <- minus_y ^ 2
  sum_power_y <-sum(power_y)
  square_y <- sqrt(sum_power_y)
  product_square <- square_x*square_y
  PE <- sum_xy/product_square
  colnames(pearson_matrix)<-colnames(data_set)
  rownames(pearson_matrix)<-colnames(data_set)
  pearson_matrix[x,y] <- PE
}
}
View(pearson_matrix)
}


#cosine dissimilarity 
cosine_dissimilarity <- function(data_set,x,y) {
cos_sin <- 1 - cosine_similarity(data_set,x,y)
return(cos_sin)
}
```
#####DISTANCE TREES
```{r}
#function cluster dendogram 
 
cluster_dendogram <- function(data_simi){
cluster<-as.data.frame(as.table(data_simi))
dist_mat <- data_simi
dist_mat <- dist(t(data_simi), diag = F, upper = F)
dist_mat_norm <- dist_mat / max(dist_mat) 
hclus <- hclust(dist_mat_norm,method ="single")
as.dendrogram(hclus)
plot(hclus)
}



#example pearson_coefficient 
png(filename = "single_pearson.png",width = 980)
pearson_coefficient_matrix(GTEX.data_num,54)
cluster_dendogram(pearson_matrix)
dev.off()

#example cosine similarity 
png(filename = "single_cosine.png",width = 980)
cosine_similarity_matrix(GTEX.data_num,54)
cluster_dendogram(cosine_simi)
dev.off()



#standard deviations 
#example of actual standard deviations
#example cosine similarity 
png(filename = "single_sdev.png",width = 980)
actual_sdev_matrix(GTEX_log,mean_log,sd_log,19193,54)
cluster_dendogram(simi_matrix)
dev.off()


mat <- cosine_simi 
dist_mat <- matrix(nrow = length(54), ncol = length(54))
dist_mat <- dist(t(mat), diag = F, upper = F)
dist_mat_norm <- dist_mat / max(dist_mat)  ## constrain domain of distance values to 0-1
dist_df_temp <- data.frame(t(combn(54,2)), as.numeric(dist_mat_norm), stringsAsFactors = F)
#names(dist_df_temp) <- c("sample1","sample2", "norm_distance")
hist(dist_mat_norm,breaks = 1000)
distance_tree <- GeneSpecificityFuncs::LMB_htf.dist_tree(dist_df = dist_df_temp)






```
### Weights functions 
```{r}
count_number_descendant<- function(node) {
  if(is.na(node$left_child) & is.na(node$right_child)){
    return(1) }
  else{
   return (count_number_descendant(node$left_child)+count_number_descendant(node$right_child))}
}


calc_node_weight <- function(node, parent_weight = 0) {
node$weight <-  (node$dist_to_parent / count_number_descendant(node)) + parent_weight
	if(!all(is.na(node[["left_child"]]))){
	  	 node[["left_child"]]<-calc_node_weight(node[["left_child"]],parent_weight = node$weight)
       node[["right_child"]]<-calc_node_weight(node[["right_child"]],parent_weight = node$weight)
	}
return(node)
}

 return_sample_weights <- function(node){
   if(is.na(node$left_child) & is.na(node$right_child)){
     return(data.frame(name = node$name,weight = node$weight))
   }
 return(rbind(return_sample_weights(node[["left_child"]]),return_sample_weights(node[["right_child"]])))
}
#gives vector of weights
weights_tree <-return_sample_weights(tree)
list_names<-(colnames(GTEX.data_num))
for (i in 1:54){
  weights_tree$name[weights_tree$name == i] <- list_names[i]
  
}

```
###example of weights vector 
#Cosine Similarity
```{r}

#example cosine similarity 
cosine_simi<- matrix(0, nrow = 54, ncol = 54)
for(y in 1:54) {
  for(x in 1:54)  {
product_xy <- GTEX.data_num[,x] * GTEX.data_num[,y]
sum_xy <- sum(product_xy)
magnitude_x <- GTEX.data_num[,x]^2
magnitude_x<- sum(magnitude_x)
magn_x <- sqrt(magnitude_x)
magnitude_y <- GTEX.data_num[,y]^2
magnitude_y <- sum(magnitude_y)
magn_y <- sqrt(magnitude_y)
magn_z <- magn_x * magn_y
cos_sin <-  sum_xy/magn_z
colnames(cosine_simi)<-colnames(GTEX.data_num)
rownames(cosine_simi)<-colnames(GTEX.data_num)
cosine_simi[x,y] <- cos_sin

  }
}
mat <- cosine_simi


## calculate distance matrix
dist_mat <- dist(t(mat), diag = F, upper = F)
dist_mat_norm <- dist_mat / max(dist_mat)  ## constrain domain of distance values to 0-1
dist_df_temp <- data.frame(t(combn(54,2)), as.numeric(dist_mat_norm), stringsAsFactors = F)
names(dist_df_temp) <- c("sample1","sample2", "norm_distance")
hist(dist_mat_norm,breaks = 1000)

dist_vector<-as.vector(unlist(dist_df_temp))


distance_tree <- GeneSpecificityFuncs::LMB_htf.dist_tree(dist_df = dist_df_temp)
count_number_descendant(distance_tree)
tree<-calc_node_weight(distance_tree)
tree_vector<-as.vector(unlist(tree))
cosine_tree<-data.frame(tree_vector)

weights_cosine<-return_sample_weights(tree)

list_names<-(colnames(GTEX.data_num))
for (i in 1:54){
  weights_cosine$name[weights_cosine$name == i] <- list_names[i]
  
}




```
#Standard deviations
```{r}
actu_sdev <- matrix(0, nrow = 19193, ncol = 54) 
for(j in 1:54) {
  for(i in 1:19193)  {
   actu_sdev[i,j] <- (GTEX_log[i,j] - mean_log[i])/sd_log[i]
}      
}

actu_sdev <-replace(actu_sdev, is.na(actu_sdev), 0)
n <- matrix(0, nrow = 54, ncol = 54)
dot_product_matrix <- matrix(0, nrow = 54, ncol = 54)
for(G1 in 1:54) {
  for(G2 in 1:54)  {
   n <- actu_sdev[,G1]*actu_sdev[,G2]
   dot_product_matrix [G2,G1]<- sum(n)
}
}
diag_val <- diag(dot_product_matrix )
diag_matrix <- data.matrix(diag_val)
simi_matrix<- matrix(0, nrow = 54, ncol = 54)
for(G1 in 1:54) {
  for(G2 in 1:54)  {
 simi_matrix[G1,G2]<-  dot_product_matrix [G1,G2]/(max(diag_matrix [G1],diag_matrix [G2]))
}
}
colnames(simi_matrix)<-colnames(GTEX.data_num)
rownames(simi_matrix)<-colnames(GTEX.data_num)


simi <-simi_matrix
## calculate distance matrix
dist_simi <- dist(t(simi), diag = F, upper = F)
dist_simi_norm <- dist_simi / max(dist_simi)  ## constrain domain of distance values to 0-1
dist_simi_temp <- data.frame(t(combn(54,2)), as.numeric(dist_simi_norm), stringsAsFactors = F)
names(dist_simi_temp) <- c("sample1","sample2", "norm_distance")
hist(dist_simi_norm,breaks = 1000)

dist_simi_vector<-as.vector(unlist(dist_simi_temp))


distance_simi_tree <- GeneSpecificityFuncs::LMB_htf.dist_tree(dist_df = dist_simi_temp)
count_number_descendant(distance_simi_tree)
tree_simi<-calc_node_weight(distance_simi_tree)
tree_simi_vector<-as.vector(unlist(tree_simi))
simi_tree<-data.frame(tree_simi_vector)

weights_simi<-return_sample_weights(tree_simi)

list_names<-(colnames(GTEX.data_num))
for (i in 1:54){
  weights_simi$name[weights_simi$name == i] <- list_names[i]
  
}




```
#Pearson Coefficients
```{r}
  pearson_matrix<- matrix(0, nrow = 54, ncol = 54)
  for(y in 1:54) {
     for(x in 1:54)  {
  mean_x <- mean(GTEX.data_num[,x])
  mean_y <- mean(GTEX.data_num[,y])
  minus_x <- (GTEX.data_num[,x] - mean_x)
  minus_y <- (GTEX.data_num[,y] - mean_y)
  product_xy <- minus_x*minus_y
  sum_xy<- sum(product_xy)
  power_x <- minus_x ^ 2 
  sum_power_x <-sum(power_x)
  square_x <- sqrt(sum_power_x)
  power_y <- minus_y ^ 2
  sum_power_y <-sum(power_y)
  square_y <- sqrt(sum_power_y)
  product_square <- square_x*square_y
  PE <- sum_xy/product_square
  colnames(pearson_matrix)<-colnames(GTEX.data_num)
  rownames(pearson_matrix)<-colnames(GTEX.data_num)
  pearson_matrix[x,y] <- PE
}
}

pearson <-pearson_matrix
## calculate distance matrix
dist_pearson <- dist(t(pearson), diag = F, upper = F)
dist_pearson_norm <- dist_pearson / max(dist_pearson)  ## constrain domain of distance values to 0-1
dist_pearson_temp <- data.frame(t(combn(54,2)), as.numeric(dist_pearson_norm), stringsAsFactors = F)
names(dist_pearson_temp) <- c("sample1","sample2", "norm_distance")
hist(dist_pearson_norm,breaks = 1000)

dist_pearson_vector<-as.vector(unlist(dist_pearson_temp))


distance_pearson_tree <- GeneSpecificityFuncs::LMB_htf.dist_tree(dist_df = dist_pearson_temp)
count_number_descendant(distance_pearson_tree)
tree_pearson<-calc_node_weight(distance_pearson_tree)
tree_pearson_vector<-as.vector(unlist(tree_pearson))
pearson_tree<-data.frame(tree_pearson_vector)


weights_pearson<-return_sample_weights(tree_pearson)

list_names<-(colnames(GTEX.data_num))
for (i in 1:54){
  weights_pearson$name[weights_pearson$name == i] <- list_names[i]
  
}



```